# Generated by Django 6.0.2 on 2026-03-01 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('idens', models.AutoField(primary_key=True, serialize=False)),
                ('numens', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('departement', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=30)),
                ('specialite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('idcours', models.AutoField(primary_key=True, serialize=False)),
                ('code_cours', models.CharField(max_length=20, unique=True)),
                ('intitule', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('credit', models.PositiveSmallIntegerField()),
                ('semestre', models.CharField(max_length=20)),
                ('niveau', models.CharField(max_length=30)),
                ('departement', models.CharField(max_length=50)),
                ('prerequis', models.TextField(blank=True)),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='university.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('idetu', models.AutoField(primary_key=True, serialize=False)),
                ('num_carte', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(blank=True, max_length=15)),
                ('filiere', models.CharField(max_length=50)),
                ('annee_entree', models.PositiveSmallIntegerField()),
                ('date_naissance', models.DateField()),
                ('cours', models.ManyToManyField(related_name='etudiants', to='university.cours')),
            ],
        ),
    ]
